---
title: "Análisis caso control negativo en el tiempo desde prueba"
output: 
  html_document:
    code_folding: show
    highlight: espresso
    css: 
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes  
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 3     
editor_options: 
  chunk_output_type: inline
---


```{r set-global-options, echo = FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = TRUE, 
                      cache = FALSE,
                      include = TRUE,
                      collapse = FALSE,
                       dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = TRUE,
                      fig.path="Figures/",  # Set the figure options
                      fig.align = "center", 
                      fig.width = 12,
                      fig.height = 12)
```

```{r librerias, echo=FALSE, message=FALSE, include=FALSE, warning=FALSE}
# source("0_a_librerias.R")
# ya se cargan cuando se carguen las funciones

```

```{r}
# función para cargar un .Rmd como si se hiciese source de un .r---------------
source_rmd = function(file, ...) {
  tmp_file = tempfile(fileext = ".R")
  on.exit(unlink(tmp_file), add = TRUE)
  knitr::purl(file, output = tmp_file)
  source(file = tmp_file, ...)
}

```

```{r}
# cargar funciones de 0_funciones----------------------------------------------
if (!exists("se_ha_cargado_f")) {
suppressMessages(source_rmd("0_b_funciones.rmd"))
}

```


```{r cargar-datos, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# cargar datos-----------------------------------------------------------------
pobana_2 <- readRDS(file = file.path("Resultados", "pobana_2.RDS"))
test220613_cleaned <- readRDS(file = file.path("Datos", "Procesados", 
                                             "test220613_cleaned.RDS"))

```

```{r}
# check fecha test
test220613_cleaned %>% arrange(freg)
# hay 2 test con fecha 2012, pero son negativos. No problem

```


```{r}
# descriptivo test, fcv1 y fih1
test220613_cleaned2 <- test220613_cleaned %>% 
  filter(tpos == TRUE) %>% 
  select(id, ftes) %>%
  group_by(id) %>% 
  mutate(n = 1:n()) %>% 
  ungroup()

test220613_cleaned3 <- test220613_cleaned2 %>%   
pivot_wider(id_cols = id,
            names_from = n,
            names_prefix = "f_test_positivo_",
            values_from = ftes)

pobana_con_test <- pobana_2  %>% 
  select(id, fcv1, fcv2, fih1) %>%
  left_join(test220613_cleaned3)

# comprobar que las fechas están bien------------------------------------------
pobana_con_test %>% filter(!is.na(fcv1), is.na(f_test_positivo_1))
pobana_con_test %>% filter(is.na(fcv1), !is.na(f_test_positivo_1))
# OK

```

# Análisis población general

```{r}
data_out <- f_matching_tncc(
  data = pobana_2,
  tiempo_0 = ymd("2022-01-03"),
  caso_control_var = "tpos",
  caso_control_date = "ftes",
  base_test = test220613_cleaned,
  vector_match = c("gen", "migran", "p_edad_cat"),
  birth_date = "fnac",
  age_first = 40,
  age_last = 90,
  age_by = 5)

data_out %>% count(caso_control)

```

```{r}
lista_out <- f_matching_tncc_mult(
  data = pobana_2,
  f_ini = ymd("2022-01-03"),
  f_fin = ymd("2022-06-13"),
  caso_control_var = "tpos",
  caso_control_date = "ftes",
  base_test = test220613_cleaned,
  vector_match = c("gen", "migran", "p_edad_cat"),
  birth_date = "fnac",
  age_first = 40,
  age_last = 90,
  age_by = 5)

lista_out$tt_tibble %>% count(caso_control)

```



```{r}
# logística condicional
data_out2 <- lista_out$tt_tibble %>% 
  mutate(tratamiento = case_when(
    is.na(fvc2) & is.na(fcv1_prev) ~ 1,
    is.na(fvc2) & !is.na(fcv1_prev) ~ 2,
    !is.na(fvc2) & is.na(fvc3) & is.na(fcv1_prev) ~ 3,
    !is.na(fvc2) & is.na(fvc3) & !is.na(fcv1_prev) ~ 4,
    !is.na(fvc3) & is.na(fcv1_prev) ~ 5,
    !is.na(fvc3) & !is.na(fcv1_prev) ~ 6
  )) %>% 
  mutate(tratamiento = as_factor(tratamiento))

data_out2 %>% skimr::skim(fcv1_prev)

data_out2 %>% count(tratamiento)

pob_general <- clogit(caso_control ~ tratamiento + strata(par), data = data_out2)

```

```{r}
summary(pob_general)

```

# Análisis mayores de 40. Análisis de booster.

```{r}
# se crean listas que dependen del proyecto------------------------------------
lista_exclusion_dep_tncc <- list(
  criterios = list(
  c1 = "Excluyendo: edad < 40 años en tiempo_0...", 
  c2 = "Excluyendo: pauta incompleta 90 días antes del tiempo_0..."
  ),
  variables = list(
  v2 = "fnac_40",
  v3 = "fpauta_90"
  ),
  tipo_var = list(
    "inc",
    "inc"
    )
  )

```


```{r}
data_out <- f_matching_tncc(
  data = pobana_2,
  tiempo_0 = "2022-01-03",
  caso_control_var = "tpos",
  caso_control_date = "ftes",
  base_test = test220613_cleaned,
  vector_match = c("gen", "migran", "p_edad_cat"),
  crit_exc = lista_exclusion_dep_tncc,
  birth_date = "fnac",
  age_first = 40,
  age_last = 90,
  age_by = 5)

data_out %>% count(caso_control)

```

```{r}
lista_out <- f_matching_tncc_mult(
  data = pobana_2,
  crit_exc = lista_exclusion_dep_tncc,
  f_ini = "2022-01-03",
  f_fin = "2022-06-13",
  caso_control_var = "tpos",
  caso_control_date = "ftes",
  base_test = test220613_cleaned,
  vector_match = c("gen", "migran", "p_edad_cat"),
  birth_date = "fnac",
  age_first = 40,
  age_last = 90,
  age_by = 5,
  verbose = FALSE)

lista_out$tt_tibble %>% count(caso_control)

```



```{r}
# logística condicional
data_out2 <- lista_out$tt_tibble %>% 
  mutate(tratamiento = case_when(
     is.na(fvc3) & is.na(fcv1_prev) ~  1,
     is.na(fvc3) & !is.na(fcv1_prev) ~ 2,
    !is.na(fvc3) & is.na(fcv1_prev) ~  3,
    !is.na(fvc3) & !is.na(fcv1_prev) ~ 4
  )) %>% 
  mutate(tratamiento = as_factor(tratamiento))

data_out2 %>% skimr::skim(fcv1_prev)

data_out2 %>% count(tratamiento)

booster_analysis <- clogit(caso_control ~ tratamiento + strata(par), data = data_out2)

```

```{r}
summary(booster_analysis)

```
